export const CART_FAVS_REQUEST = "CART_FAVS_REQUEST";
export const CART_FAVS_SUCCESS = "CART_FAVS_SUCCESS";
export const CART_FAVS_FAILURE = "CART_FAVS_FAILURE";
export const UPDATE_CART_FAV = "UPDATE_CART_FAV";
